### ISSUE TITLE
[BUG] - Annotators are shown in databrowser user filter list

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#101]
**Describe the bug**
In my case, Henrik and Moritz are ANNOTATORS. I only want to see ENGINEERS and EXPERTS here.
<img width="372" alt="Bildschirmfoto 2022-09-20 um 14 00 53" src="https://user-images.githubusercontent.com/62521561/191252138-1b1fa2e2-0d90-45d2-813a-ef3a9972f7c9.png">
 is.

**To Reproduce**
1. Create an org with two users, one engineer/expert and one annotator
2. Create a project and look into the filter bar :)

**Expected behavior**
Only show engineers and experts

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 1.2.0

**Additional context**
\-

**Comment by JWittmeyer** [comment]
solved in annotator PR
