### ISSUE TITLE
Run on 10 should be used everywhere where it makes sense

### ISSUE THREAD

**Issue by lumburovskalina** [code-kern-ai/refinery#102]
**Feature request**
Run on 10 records option is a good way to test a function. This helps for faster results and see if your function is working as expected instead of testing it on all records every time. Example of this feature is implemented on zero-shot page and the same can be done for labeling functions. On every feature we want to include it as a functionality. 

**Describe the solution you'd like**
Implement 'Run on 10' records on labeling function and on every next feature where is makes sense. Each of those 10 records should have a 'View' option that displays a modal with the details of the records.

**Comment by JWittmeyer** [comment]
Added in https://github.com/code-kern-ai/refinery-ui/pull/66
