### ISSUE TITLE
[BUG] - spacy Doc sentiment is always 0.0

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#103]
**Describe the bug**
The spacy Doc sentiment is always 0.0 for the attributes of my records.

**To Reproduce**
1. Go to a project of yours
2. Make a labeling function printing the sentiment of one of your attributes, e.g. "print(record["headline"].sentiment)" in AG_News
3. Observe the sentiment output, which is always 0.0

**Expected behavior**
The sentiment should reflect the true sentiment of the attribute, which is NOT always 0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/57487741/191485151-c17aed62-1ef6-4c06-893c-e8c99bc2bed2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 1.2.0

**Additional context**
-

**Comment by jhoetter** [comment]
I need to look up the source for this, but if I remember correctly, the `md` (medium) tokenizers don't contain a sentiment pipeline. We can offer to also integrate `lg` models, which have both a higher precision in their entity recognition and sentiment.

Again, this is off the top of my head, I need to research this again to be 100% sure

**Comment by JWittmeyer** [comment]
Sentiment isn't a field that is automatically filled by [spacy](https://github.com/explosion/spaCy/discussions/12547#discussioncomment-5660256)
