### ISSUE TITLE
[UX] - Record Export Editor

### ISSUE THREAD

**Issue by SirDegraf** [code-kern-ai/refinery#128]
For the project snapshot we already have a cool editor to customize the content of the exported file. A similar approach for the export of records would add value, because we could introduce the functionality to include or exclude all or specific labels for a record export file. So as an user you would be able to export just the original records, the original records with the calculated attributes, the records and label data or a combination of all these.

**Comment by JWittmeyer** [comment]
First version through the integration of https://github.com/code-kern-ai/refinery/issues/143
Additional options will follow in the future
