### ISSUE TITLE
[BUG] - Deletion of user does not work properly atm

### ISSUE THREAD

**Issue by SirDegraf** [code-kern-ai/refinery#132]
In our admin dashboard we have the functionality to delete registered users but atm it does not function properly because it only reloads the page

**Comment by lumburovskalina** [comment]
Steps to fix bug:

1. Debugging why bug is not present locally but only on dev.
2. Implementing solution.
3.  Testing and review.

**Comment by JWittmeyer** [comment]
Doesnt happen anymore
