### ISSUE TITLE
Filter option for commented records

### ISSUE THREAD

**Issue by SirDegraf** [code-kern-ai/refinery#136]
We could introduce a filter functionality for commented records because in some cases these could be the interesting ones a user wants to see

**Comment by FelixKirsch** [comment]
**Is your feature request related to a problem? Please describe.**
Especially, on views that allow many different categories of comments, it can happen that the number of comments becomes pretty large. In this case, finding a specific comment can be tedious work.

**Describe the solution you'd like**
Introduce filtering for comments. Options could be "Show all", "Specific type" and "specific type and instance". This way the number of displayed comments could be reduced to the ones in which the user is interested.

**Additional context**
Test findings v1.5.0

**Comment by JWittmeyer** [comment]
Backen integration is included frontend is planned:

1. Endpoint for a list of record ids to display in the databrowser:

```
query ($projectId: ID!, $recordIds: [ID]!) {
  recordComments(projectId: $projectId, recordIds: $recordIds)
}

example variables:
  "projectId": "25bae79e-a0d6-4dc1-b9d0-9cbb01ce53f6",
  "recordIds": ["ed59c85f-5970-4421-8f6b-fb1cbf31d069"]

```

2. Subquery for filtering if a record has a comment:
```
let element = {
    SUBQUERY_TYPE: 'BLACKLIST' || 'WHITELIST',
    SUBQUERIES: [{
        QUERY_TEMPLATE: 'SUBQUERY_HAS_COMMENTS',
        VALUES: [UserManager.getUser().id],
    }],
};
```

**Comment by lumburovskalina** [comment]
Steps to implement:
- Add checkbox on the comment section to display all comments
- Add new section in the data browser: Has comments
- Implement queries and mutations for the tasks
- Testing and review
