### ISSUE TITLE
[BUG] - Empty fields when uploading records with new attributes

### ISSUE THREAD

**Issue by SirDegraf** [code-kern-ai/refinery#144]
**Describe the bug**
If a record gets uploaded into an existing project with records in it with a new attribute (which is not yet present in the project) it gets created and all of the other records get an empty attribute field added in the data browser. They are most certainly not added into the database (not 100% sure) but the data browsers appearance can make it seem like empty field were added.

**To Reproduce**
It can be reproduced by creating a sample Clickbait project and then upload the dataset "clickbait_abc_extension_1.json" out of the referenced [test-sets.zip](https://github.com/code-kern-ai/refinery-gateway/files/9775463/test-sets.zip)/1 into the clickbait project.

**Expected behavior**
I don't really know what the best solution is here but i think the way it is at the moment could confuse many users. Maybe display that these empty attributes are not really existent for the record, but like i said, a solution is still to be thought of.

**Screenshots**
<img width="592" alt="image" src="https://user-images.githubusercontent.com/70139038/195592675-fd719879-3cbf-417f-b734-a27e45038877.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by JWittmeyer** [comment]
imo a marker "not present in record" would be easy to include and help with the confusion :)

**Comment by lumburovskalina** [comment]
Steps to fix bug:
1. Upload the additional record to reproduce bug.  (15minutes)
2. Set condition in the data-browser and labeling page when the attribute is not present (30minutes)
3. If the condition is true, set a marker (maybe a warning icon)? (15minutes)
4. Testing and review (1h)

Estimation time: 2h
