### ISSUE TITLE
Data browser filter extensions for datatypes

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#153]
**Is your feature request related to a problem? Please describe.**
Currently, refinery supports different attribute types. E.g. Integer, Text, Boolean,...
The types are good but only usable to some extent in the data browser.
E.g. all attributes are filtered string like with (CONTAINS, BEGINS WITH, ...)
A filter for BETWEEN (without string cast) might also be interesting for Integer.

**Describe the solution you'd like**
Extend Filter capabilities to different data types without string cast & add additional filter options

**Additional context**
Interesting filter:
Integer, Float, Text, Category: BETWEEN, EQUAL, GREATER, GREATER EQUAL, LESS, LESS EQUAL, IN

Additional:
Boolean - True / False
Category, Text - LIKE, ILIKE, (BEGINS WITH, ENDS WITH)

For IN:
comma-separated list should be splitter and wrapped by backend to reduce hassle for UX

Note:
performance needs to be tested. Maybe a partial index and a change to jsonb instead of json is needed

**Comment by FelixKirsch** [comment]
Notes for ToDo Planning:

Input Field:
Integer, Float - only numbers
_Category - Dropdown or Freetext Field ?_ 
Text - Free Text Field
Boolean - Dropdown

Filters:
Any Attribute - as for text
Integer, Float - BETWEEN, EQUAL, GREATER (EQUAL), LESS (EQUAL), IN
_Category - EQUAL, NOT EQUAL, IN or Free Text Field than as for TEXT?_
Text - CONTAINS, EQUAL, BEGINS_WITH, ENDS_WITH,  += LIKE, ILIKE
Boolean - IS (True/False)

**Comment by FelixKirsch** [comment]
Backend Tasks:
- [ ] read and understand the data browser code/queries (4h - 8h)
- [ ] implementation planning (3h)
- [ ] Definition of the frontend/backend interface (4h)
- [ ] implementation (?)
- [ ] meetings/communication (4h)
- [ ] testing (4h)

**Comment by FelixKirsch** [comment]
Define in the configuration if values for the IN operator are splitted by , or by -

**Comment by FelixKirsch** [comment]
Reminder:
IN LIKE operator specify multiple options for begins_with or ends_with, user can use % signs themselves
split IN and connect with OR

**Comment by FelixKirsch** [comment]
Changing the dropdown colors modal etc

**Comment by lumburovskalina** [comment]
Front-end tasks:
- Data browser code understanding
- Update search operator and search operator tooltip with the additional values
- Update dropdown for attributes (each option should have the type) and filter the options on the other dropdown
- Add additional input field for between option and add colors to the dropdown options
- Update parameters to the query for filtering attributes
- Define configuration in the configuration modal if the values for the IN operator are separated by "-" or ","
- Update filters on the right side with the selected values
- Discussions and meetings
- Testing and review

Steps: 
- [ ] Data browser code understanding (3h-4h)
- [ ] Update search operator and search operator tooltip with the additional values (1h)
- [ ] Update dropdown for attributes (each option should have the type) and filter the options on the other dropdown (2h-3h)
- [ ] Add additional input field for between option and add colors to the dropdown options (2h)
- [ ] Update parameters to the query for filtering attributes (2h-3h)
- [ ] Define configuration in the configuration modal if the values for the IN operator are separated by "-" or "," (3h)
- [ ] Update filters on the right side with the selected values (3h-4h)
- [ ] Discussions and meetings (3h-4h)
- [ ] Testing and review (4h)

OVERALL: 23h - 28h
