### ISSUE TITLE
Updater endpoint to set current version to newest

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#162]
**Is your feature request related to a problem? Please describe.**
The current and the newest version diverge on server instances of refinery, because these instances are not updated via the updater-service. 

**Describe the solution you'd like**
An endpoint in the updater service that sets the current version to the newest version (for dev).
Maybe, via update to newest for demo and managed. 

**Describe alternatives you've considered**
Change the version by hand in the database.

**Additional context**
test finding v1.5.0

**Comment by JWittmeyer** [comment]
part of this pr https://github.com/code-kern-ai/refinery-updater/pull/36
