### ISSUE TITLE
Add further requirements to execution environments

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#166]
**Is your feature request related to a problem? Please describe.**
I want to import the following libraries in the execution environments:
```
langdetect==1.0.9
phonenumbers==8.13.0
python-levenshtein==0.20.8
textblob==0.17.1
textstat==0.7.3
```

**Describe the solution you'd like**
Add the requirements to the exec-env parent image

**Comment by jhoetter** [comment]
```
langdetect==1.0.9
nltk==3.7
phonenumbers==8.13.0
python-levenshtein==0.20.8
textblob==0.17.1
textstat==0.7.3
translate==3.6.1
spacy==3.4.2
quantulum3==0.7.11
LeXmo==0.1.4
```

**Comment by LeonardPuettmann** [comment]
`fuzzywuzzy==0.18.0`

**Comment by JWittmeyer** [comment]
current requirements included. for new one reopen the issue

**Comment by divyanshukatiyar** [comment]
`better_profanity==0.7.0` (will mention in the readme that the module using this will work in refinery versions > 1.6)

**Comment by LeonardPuettmann** [comment]
`stemming==1.0.1`

**Comment by JWittmeyer** [comment]
`nltk.downloader words stopwords wordnet omw-1.4 brown punkt`

**Comment by JWittmeyer** [comment]
current requirements included. for new one reopen the issue

**Comment by LeonardPuettmann** [comment]
bayes_opt==1.4.2

**Comment by LeonardPuettmann** [comment]
google-search-api==2.4.1

**Comment by JWittmeyer** [comment]
included in image 1.8.0 reopen with new requirements

**Comment by LeonardPuettmannKern** [comment]
`textacy==0.12.0`

**Comment by JWittmeyer** [comment]
included in image 1.8.1 reopen with new requirements

**Comment by divyanshu404** [comment]
`scikit-optimize==0.9.0`

**Comment by JWittmeyer** [comment]
included in image 1.8.2 reopen with new requirements

**Comment by JWittmeyer** [comment]
`holidays==0.21.13`

**Comment by JWittmeyer** [comment]
`sumy==0.11.0`

**Comment by LeonardPuettmannKern** [comment]
Please update OpenAI from `openai==0.25.0` to `openai==0.27.7`. Otherwise, GPT-3.5-Turbo and GPT-4 won't be usable in refinery. Thanks! :)

**Comment by FelixKirschKern** [comment]
included in exec env image 1.11.0 reopen with new requirements

**Comment by SvenjaKern** [comment]
Please include knowledge==0.3

**Comment by SvenjaKern** [comment]
`PyPDF2==3.0.1`

**Comment by FelixKirschKern** [comment]
@SvenjaKern I added `pypdf==3.15.5` instead. pypdf and pypdf2 have the same maintainer and he wants the community to switch to pypdf (https://stackoverflow.com/questions/63199763/maintained-alternatives-to-pypdf2, first answer). He states that both should be similar. PyPDF2 also raised a dependabot alert, which also suggested the switch to pypdf as fix.

Please check if the new brick also works with pypdf. If that's the case, you can simply close the issue.
Otherwise, I will add pypdf2 instead.

**Comment by LeonardPuettmannKern** [comment]
@FelixKirschKern Please add `tiktoken==0.4.0` and remove `pypdf==3.15.5` if it was added, as it's not needed. Thanks!

**Comment by JWittmeyer** [comment]
also increase psycopg2-binary version to `psycopg2-binary==2.9.7`

**Comment by FelixKirschKern** [comment]
Added tiktoken==0.4.0 and removed pypdf==3.15.5, updated urllib3

**Comment by JWittmeyer** [comment]
increase psycopg2-binary version to `psycopg2-binary==2.9.7` (or maybe even higher)

**Comment by FelixKirschKern** [comment]
Updated psycopg2-binary and added language support for japanese
