### ISSUE TITLE
[UX] - Adding comments in the labeling view will re-label my data

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#168]
**What would you improve?**
When I input my comment in the labeling view, all the keyboard shortcuts get triggered. That means I will accidentally re-label the data and switch between records when writing a comment. I would expect the keyboard shortcuts to be disabled when writing a comment.

Real-world example:
![comment_issue](https://user-images.githubusercontent.com/57487741/200813763-d8423f6d-c2df-40c7-ac49-e27a86217331.gif)

**Comment by JWittmeyer** [comment]
This was fixed at some point -> need to look into it again :)
