### ISSUE TITLE
[BUG] - Crowd heuristic can be run/executed, which just results in errors.

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#169]
**Describe the bug**
In the heuristics overview the user is able to select heuristics by clicking on their checkboxes. With the selected heuristics, the user can execute certain actions. One of those actions is "Run selected". The crowd heuristic can be selected and can be run with the "run selected" action, which leads to errors as this action is not intended for a crowd heuristic. 
**To Reproduce**
1. Make a crowd heuristic
2. Select it in the heuristics overview
3. Click "Actions" -> "run selected"

**Expected behavior**
You should not be able to "Run selected" when a crowd heuristic is selected and that should also be displayed as a hover tooltip so the user knows what to do. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57487741/200848090-f9c1c6dc-e944-467a-843b-bb0298288917.png)
![image](https://user-images.githubusercontent.com/57487741/200848130-44645e83-ff95-435b-a4bc-2924e2db25e5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version v1.5.0

**Additional context**
-

**Comment by JWittmeyer** [comment]
Backend will filter for crowd heuristics to simply not run them
UI will receive a tooltip with "Except Crowd"
