### ISSUE TITLE
[UX] - Add logos of the heuristics to the cards on the heuristics overview

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#177]
**What would you improve?**
On the heuristics page, an overview of all created heuristics is given. They are displayed as cards. These heuristics can be of different types: labeling function, zero-shot, etc. On the dropdown 'New heuristic' each of the heuristics has its own logo.
<img width="363" alt="Screenshot 2022-11-16 at 09 33 04" src="https://user-images.githubusercontent.com/40427105/202129244-e177ff51-955f-4637-85c4-0b553e6c3744.png">
I think it would be very useful if these logos are also added to the cards of the heuristics. That way, it would be easier to distinguish between the different types even without reading the name or if the name does not state the type.
<img width="1967" alt="Screenshot 2022-11-16 at 09 30 53" src="https://user-images.githubusercontent.com/40427105/202128677-2245d606-96da-48a4-b56e-cee2ec6c8060.png">
The logo could be added in front of the name of the heuristic on the card.

**Comment by JWittmeyer** [comment]
in front of the name looked super weird so it's now below the checkbox
