### ISSUE TITLE
[BUG] - Active learning fails after deleting records

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#182]
**Describe the bug**
Active learning fails after I deleted a record that was manually labeled

**To Reproduce**
@LakshmiPanguluri please correct me if I got this wrong :)

1. Create a project and label some data manually
2. Create and run an active learner
3. Delete a record which has a manual label
4. Run said active learner again

**Expected behavior**
The active learner should skip the record, i.e. work as normal

**Screenshots**
![](https://user-images.githubusercontent.com/25331738/202253697-a8ba9065-e0a2-4171-a716-051fe3d4c55d.png)

**Desktop (please complete the following information):**
\-

**Additional context**
Mentioned by LakshmiPangukuri in the discussions thread #181

**Comment by JWittmeyer** [comment]
Im assuming this is due to a missing reupload of the embedding data after deletion

**Comment by LakshmiPanguluri** [comment]
Hi,

Thanks for the response. I am able to run after rerunning through embedding
step after deleting record.

Best Regards,
Lakshmi

**Comment by jhoetter** [comment]
Thanks, makes sense. It is in our backlog :)
