### ISSUE TITLE
[UX] - Add logout option to the demo app

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#188]
**What would you improve?**
At the moment, you can choose a role to start looking at the demo of refinery:
![image](https://user-images.githubusercontent.com/57487741/203342873-c55722c7-e8a0-4e1f-811b-7280f9e3c89f.png)

But after you've chosen your role, you cannot logout of it, so you're essentially stuck on that role:
![image](https://user-images.githubusercontent.com/57487741/203342963-b4720bb2-2246-4eda-92af-bcb063455209.png)

Of course you could clear your browser cache etc or go into incognito mode, but I doubt this will be a realistic option for people who just want to have a look around. They would probably be confused and then leave.

That is why I propose to also include a logout option, so that users can experience all roles in a single browser session!

**Comment by lumburovskalina** [comment]
Steps to implement:
- Add different condition for displaying the current dropdown (15minutes)
- Add dropdown with only one option to logout for demo users (15minutes)
- Review and testing (1h)
Estimation: 1h 30min
