### ISSUE TITLE
[BUG] - Stuck preparing download during export record data

### ISSUE THREAD

**Issue by zachschillaci27** [code-kern-ai/refinery#195]
**Describe the bug**
When attempting to export records from the settings page, I am stuck waiting for "Prepare Download" to finish. Changing the other export settings does not solve the issue. I am currently trying to download a slice of 270 records out of a dataset of 1,000 records. The records to be exported consist of the original raw data and additional manual labels.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Download records'
3. Click on 'Prepare Download'

**Expected behavior**
Given the relatively small dataset size, I would expect the download preparation to be practically instantaneous on my machine. Instead, I am left waiting an indefinite amount of time.

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Browser: Chrome
 - Version: 1.7.1

Any help would be much appreciated!

**Comment by jhoetter** [comment]
Hi @zachschillaci27, we'll look into it and will get back to with either a solution or further questions :)

**Comment by DerEchteFeuerpfeil** [comment]
Hey @zachschillaci27, thanks for reaching out!

I provided a screen-recording of me trying to reproduce the issue, which I could not. Both static and dynamic slices work well for me. Could you open the developer tools and go into the network tab to see if the queries return an error?
Also could you look into the individual versions by clicking on the version number in the bottom left and attach a screenshot of it?

![download_slice](https://user-images.githubusercontent.com/57487741/210595713-591a1fa4-b3c5-4184-ba80-169a6a68c613.gif)

**Comment by zachschillaci27** [comment]
Hi @DerEchteFeuerpfeil, thanks for the quick reply!

Sorry, I should have been more specific. The "Prepare Download" button does work on its first press, but then when I click on the .zip file for download the "Prepare Download" button gets stuck loading. Please see the network errors below:

![Screenshot 2023-01-04 at 17 23 01](https://user-images.githubusercontent.com/40636930/210601525-cdbd39c9-e172-495d-a3ac-7bcff5ef42c8.png)

As for the individual versions, please see here:

![Screenshot 2023-01-04 at 17 19 15](https://user-images.githubusercontent.com/40636930/210600728-91e346fb-61da-4573-8621-3c6ad53a0ab0.png)

**Comment by DerEchteFeuerpfeil** [comment]
I could unfortunately not reproduce the issue, but I reached out to our development team for further investigation!

If we cannot solve it asynchronously, there is also the possibility for you to join our weekly office hours on our community discord every Wednesday at 11am, where we can debug and fix it synchronously together. But that is just a heads up information, we will try our best to reproduce it on our side or ask for relevant information here in this issue in order to fix it 😃

**Comment by zachschillaci27** [comment]
Stopping and restarting Refinery from the terminal appears to have solved the issue.

Thank you for the help!

**Comment by jhoetter** [comment]
Great! :)
