### ISSUE TITLE
[BUG] - Outlier and Static slice view reset does not work in data browser

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#199]
**Describe the bug**
When clearing the filter in the data browser on a static or outlier slice, the view does not reset properly and keeps showing the filtered data.

**To Reproduce**
1. Go to data browser
2. Click on outlier or static slice
3. Click "clear filter"
4. Observe that nothing happens

**Expected behavior**
When clearing the filter in the data browser on a static or outlier slice, the view should reset properly to show all records.

**Screenshots**
![filter_reset_bug](https://user-images.githubusercontent.com/57487741/211587515-49c5bc7f-1107-40fa-950a-3b098e59462b.gif)

**Desktop (please complete the following information):**
 - OS: Win11 
 - Browser edge
 - Version 1.7.1

**Additional context**
-

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> reset results from outlier slice and show all records (1h) 
- What problems could be expected? --> there are many variables in the data browser, not sure what exactly needs to be reset (+1h)
- UI changes and notifications? --> no additional min/hours
OPTIMISTIC: 1h
PESSIMISTIC: 2h
SUM: 1h - 2h

Steps for testing:
- Testing dynamic, static and outlier slices with different filters (15 minutes)

Steps for review:
- Review (part of the whole PR)
- Fixing comments from PR (part of the whole PR)

ESTIMATION:
- Implementation: 1h - 2h
- Testing: 15minutes
- Review: (part of the whole PR)

TOTAL ESTIMATION: 1h 15 min - 2h 15 min
