### ISSUE TITLE
[UX] - Display of selected filters changes when changing the "connect by" option in the data browser 

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#202]
**What would you improve?**
This is a **really nitpicky issue**, but I've seen that the wording of the displayed filter option changes when switching the "connect by" option, which it should not need to do. It is a little irritating because your spots that something changed, but you cannot see what exactly because semantically nothing changed.

E.g. it changes from `running_id BEGINS WITH 1,22222122` to `running_id BEGINS_WITH 1,22222122` (see attached GIF for another example where there are also parentheses disappearing)

![filter wording incorrect](https://user-images.githubusercontent.com/57487741/211810632-6c1c1bae-c2bd-49ed-b03d-c16111d6a8bf.gif)

**Comment by DerEchteFeuerpfeil** [comment]
We could also get rid of the "case sensitive" option for this numeric attribute 😬

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> the operators are not displayed the same for conenct by and/or, check the active search parameters how are changed in every condition (1h)
- What problems could be expected? --> Replacing operators without _ may require additional converting back with _  (15min - 30min)
- UI changes and notifications? --> get rid of case sensitive option for numeric attribute(15min)
OPTIMISTIC: 1h 30min 
PESSIMISTIC: 1h 45min
SUM: 1h 30min - 1h 45min

Steps for testing:
- Testing different options with connect and/or (15min)

Steps for review:
- Review (part of the whole PR)
- Fixing comments from PR (part of the whole PR)

ESTIMATION:
- Implementation: 1h 30min - 1h 45min
- Testing: 15minutes
- Review: (part of the whole PR)

TOTAL ESTIMATION: 1h 45 min - 2h
