### ISSUE TITLE
[UX] - Allow the usage of arrow keys when filtering for an integer attribute

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#203]
**What would you improve?**
I cannot use arrow keys to reposition my cursor in the value field of the attribute filter when filtering for an integer attribute, which is annoying because I might want to add a wildcard before the current number and I have to delete everything, then insert the wildcard, and then re-enter everything.

![image](https://user-images.githubusercontent.com/57487741/211823340-3d67e390-623e-4ae2-925a-0dbfbe41bc9d.png)

**Comment by lumburovskalina** [comment]
Steps to implement:

- What is the core solution? --> allow arrows in the input field when filtering attributes (1h)
- What problems could be expected? --> different limitations for different types and operators, I assume there may be some issues (30min - 1h)
- UI changes and notifications? --> no additional min/hours
OPTIMISTIC: 1h 30 min
PESSIMISTIC: 2h
SUM: 1h 30 min - 2h

Steps for testing:
- Testing different options with different attribute types and operators (15minutes)

Steps for review:
- Review (part of the whole PR)
- Fixing comments from PR (part of the whole PR)

ESTIMATION:
- Implementation: 1h 30min - 2h
- Testing: 15minutes
- Review: (part of the whole PR)
TOTAL ESTIMATION: 1h 45 min - 2h 15 min
