### ISSUE TITLE
[BUG] - Multiple attribute filters to not combine properly

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#210]
**Describe the bug**
When filtering for more than one attribute filter, it should display the intersection of it. Currently this is not the case (see screenshot). My suspicion is that this has something to do with the "any attribute" filter setting. If condition it on actual attributes I cannot create such an inconsistent state, but am not 100% sure.

Also, if I search for a text in the "any attribute" then this bug does not happen, only if I search for a number (see GIF). There might be other combinations with different operators where this fails, though. But that might be valuable information for bug identification.

**To Reproduce**
1. Go to data browser in AG News project
2. Create attribute filter with "running_id" EQUAL 501
3. Create another attribute filter with "any attribute" CONTAINS 7

**Expected behavior**
There should be no record displayed as both conditions at the same time are not true on any record

**Screenshots**
![image](https://user-images.githubusercontent.com/57487741/212322462-681bb1e6-5435-41fb-a637-1e3af9bb4f39.png)
![data_browser_filter_multiple_bug](https://user-images.githubusercontent.com/57487741/212322481-9225aa83-e9fc-4f31-aed8-1fddfc6793a9.gif)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser edge
 - Version 1.7.1
 
**Additional context**
-

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> 
1. Debugging where the error occurs if it is on the FE or BE side and where exactly it happens (1h)
2. Finding solution why the intersection does not happen (1h)
- What problems could be expected? --> I would assume there will be some additional time for debugging/fixing especially if it is on the BE side - less known code (30min - 1h) 
- UI changes and notifications? --> no additional min/hours
OPTIMISTIC: 2h - 2h 30min
PESSIMISTIC: 3h
SUM: 2h-3h

Steps for testing:
- Testing if single filter and filters with intersection work as expected (15 minutes)

Steps for review:
- Review (part of the whole PR)
- Fixing comments from PR (part of the whole PR)

ESTIMATION:
- Implementation: 2h - 3h
- Testing: 15minutes
- Review: (part of the whole PR)

TOTAL ESTIMATION: 2h 15 min - 3h 15 min
