### ISSUE TITLE
[UX] - Filter wording of "ML-label" as "manual label" could be confusing

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#211]
**What would you improve?**
Currently, when you set a manual label filter in the data browser, you get the abbreviation "ML-label" displayed. As "ML" is a common abbreviation for Machine Learning, this might be rather confusing. I would just lose the "L" and call it "M-label".

![image](https://user-images.githubusercontent.com/57487741/212883030-c1bdb33d-30e6-456e-a2ac-57b3d4e090db.png)

**Comment by JWittmeyer** [comment]
should be 'M'
