### ISSUE TITLE
[BUG] - Proposals for embedding configuration string not working for token embeddings

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#217]
**Describe the bug**
Adding an embedding is handled by a modal, where the user can select the target attribute, granularity, and configuration.
For the configuration different proposals are provided in a dropdown menu. This dropdown is empty when switching to token embeddings and also stays empty on changing back to attribute embeddings

**To Reproduce**
1. Open the settings page
2. Click on 'Generate embedding'
3. Select 'Token' as granularity
4. See that no proposals are made for token embeddings

**Expected behavior**
Show configuration string proposals for token embeddings.

**Screenshots**
<img width="493" alt="Screenshot 2023-01-26 at 14 55 30" src="https://user-images.githubusercontent.com/40427105/214853701-c68db7b4-5f3a-46dc-8cd8-fef7995d18e9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - dev Version of refinery (26.01.2023)

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> 
1. Check if the embedding dictionary has the right values as it is created (15minutes)
2. Check if the suggestions list is still there on change event (15minutes)
3. Check if there is some issue with UI display (hidden/block) (15minutes)
4. Check the values on hidden and force hidden in the embeddings component (15minutes)

- What problems could be expected? --> 
1. If none of the above mentioned is the issue, further debugging about other possible bugs(1h-2h)
- UI changes and notifications? --> no additional min/hours
OPTIMISTIC: 2h (depends on the test checks from above) 
PESSIMISTIC: 3h
SUM: 2h - 3h

Steps for testing:
- Testing feature, testing adding embeddings, search bar for suggestions and project-settings page (15 minutes)

Steps for review:
- Review (30minutes)
- Fixing comments from PR (15min - 30 minutes)

ESTIMATION:
- Implementation: 2h - 3h
- Testing: 15minutes
- Review: (30 - 45minutes)

TOTAL ESTIMATION: 2h 45 min - 3h 30 min
