### ISSUE TITLE
[BUG] - Attribute calculation function name in monaco editor

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#218]
**Describe the bug**
When creating a new attribute the function code in the monaco editor holds ac instead of the function name. A short switch can be noticed

**To Reproduce**
1. Go to settings
2. Click on new attribute (e.g. text)
3. Use a brick (e.g. language detection)
4. See the function name 

Also noticeable it seems to run without any issues however it looks a bit odd having the name of the attribute diverging form the one in the code window.

**Expected behavior**
Same name with the attribute

**Screenshots**
![image](https://user-images.githubusercontent.com/91723236/215444435-d1858153-8ef7-487a-9943-26e1a01b18a7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 1.7.1 (dev so maybe 1.8.0)

**Additional context**
Happened during streaming of new platform on Jens pc -- so maybe also performance/platform related (though very unlikely)

**Comment by LeonardPuettmann** [comment]
Encountered the same problem today. The attribute is still usable though.

![problem](https://user-images.githubusercontent.com/72195901/215479875-e4308762-0e3c-4154-a6f5-6fc556fddeb9.png)

Desktop (please complete the following information):

- OS: Windows 11 Pro
- Browser Edge Chromium
- Version 1.7.1 (dev so maybe 1.8.0)

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> 
1. Check if current attribute is stored correct (15min)
2. Check when the form value changes (1h-2h)

- What problems could be expected? --> 
1. May have issue with search from scratch? (30min)
- UI changes and notifications? --> no additional min/hours

Steps for testing:
- Testing attribute calculation with attribute names (15min)

Steps for review:
- Review (30minutes)
- Fixing comments from PR (15min - 30 minutes)

ESTIMATION:
- Implementation: 1h 15min - 2h 15min
- Testing: 15minutes
- Review: (30 - 45minutes)

TOTAL ESTIMATION: 2h - 2h 45 min
