### ISSUE TITLE
[BUG] - data browser filter for empty doesn't work

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#219]
**Describe the bug**
filtering for equal empty return all records an not just the ones with no entry

**To Reproduce**
1. Go to data browser
2. Expand attributes
3. Change filter to equal
4. (Any attribute equal '')
5. all records are shown

**Expected behavior**
only show the ones with at least one attribute none existent

**Screenshots**
![image](https://user-images.githubusercontent.com/91723236/215761042-661537e4-1dda-403d-8a3d-c8be845d8cfb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 1.7.1 dev (so more like 1.8.0)

**Additional context**
happens for both any attribute and specific attribute selected

**Comment by lumburovskalina** [comment]
Steps to implement: 
- What is the core solution? --> 
1. Debugging where the issue occurs - FE/BE? (1h)
2. Probably BE? - fixing condition in sql query - searching for none existent attributes (1h)
3. Applied for both Any attribute and specific attribute (15minutes)

- What problems could be expected? --> no additional time
- UI changes and notifications? --> no additional time

Steps for testing:
- Testing if all filters work as expected (15minutes)

Steps for review:
- Review (15minutes)
- Fixing comments from PR (15minutes- 30minutes)

ESTIMATION:
- Implementation: 2h 15min
- Testing: 15min
- Review: 30minutes - 45minutes

TOTAL ESTIMATION: 3h - 3h 15minutes
