### ISSUE TITLE
[BUG] - Highlighting of current page seems to have issues from time to time

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#220]
**Describe the bug**
The page you are currently viewing in refinery is highlighted on the left side in green. This seems to sometimes run into issues. There wasn't any sure way to reproduce found yet

**Expected behavior**
Only the page that is currently being visited should be highlighted

**Screenshots**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/91723236/215991835-53c0efe5-8ea7-4e91-9c0f-c5e56b36a12c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 1.7.1 (dev)

**Comment by lumburovskalina** [comment]
We haven't experienced the issue so far. I am closing it since it's an old issue.
