### ISSUE TITLE
[BUG] - Lookup lists that are not valid Python variable names break the labeling function calculation

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery#221]
**Describe the bug**
Lookup lists that are not valid variable names break the labeling function calculation even when they are not used. When I removed the list called "123" (see screenshot), the calculation worked again. 

**To Reproduce**
1. Create a lookup list called "123"
2. Import some list (dsnt have to be the 123 one) from knowledge in a LF
3. Run it

**Expected behavior**
Either I shouldnt be able to create such list names or the execution environment should preface the list name with something viable like "list_"

**Screenshots**
![image](https://user-images.githubusercontent.com/57487741/216415711-9d0e8ce3-4780-4b6e-8699-d0ac901f5df4.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 1.7.1

**Additional context**
-

**Comment by JWittmeyer** [comment]
possible solution could be to enhance the `toPythonFunctionName` function and match the logic to the backend version. Also important to note is that there is a second function currently in use which works slightly different and should be replaced `asPythonVariable` 
- So no special characters (replace with '' - already included)
- _ case (whitespace changed to _ -> already included)
- lowercase (should be included but isn't part of the function atm)
- no starting numbers (prefixed with e.g. _ or list_)
