### ISSUE TITLE
[UX] - Uploading records in JSON fails with big integers

### ISSUE THREAD

**Issue by xavialex** [code-kern-ai/refinery#223]
Uploading a JSON record with an integer feature representing a timestamp in milliseconds fails. I guess this is due to a 32-bit precision overflow. Nothing critical, but at least to let you know about this special case since I haven't seen any log with detailed info about what went wrong. Example:
```json
{
    "project_id": "sadfasdf-sdfasdf-sadfasd",
    "time": 1674947091321,
}
```
https://discord.com/channels/993436333055938600/1012383333331779716/1072840690997919764

**Comment by JWittmeyer** [comment]
Hi @xavialex, what would be an acceptable solution here?

I looked through the code and the issue is that the column is recognized by pandas as timestamp. Timestamps however aren't support bei postgress json fields (how we store record data) and our application atm.

One option could be to convert anything we don't understand to string so it can at least be displayed.

**Comment by jhoetter** [comment]
@JWittmeyer not an easy and quick solution, but for the future, could we use the information that pandas recognized it as a timestamp to create a UTC timestamp and store that? We currently have data types such as Category, Text etc., so Timestamp could make sense as well.

With the long tail of implications, though, this will take a bit of time as mentioned. So just to share my thoughts, not as a solution for now if I got the problem right.

**Comment by JWittmeyer** [comment]
with time yes. I'd also love that feature. However the database has some issues with the timestamp format within json if I read the logs right. Nothing unsolvable but as you mentioned not a quick solution

**Comment by xavialex** [comment]
Thanks everyone. That sounds great. I think that the string conversion is what makes it not to fail while importing timestamp data from a CSV file. In any case, the issue is more like a warning for people facing similar problems while uploading JSON data.

**Comment by JWittmeyer** [comment]
We closed this since none text, unknown type columns will now (v1.8) be converted to Text before uploading. For new datatype support we will open a new issue
