### ISSUE TITLE
[BUG] - Adding a comment to specific record on the project-settings page shows the comment for all records

### ISSUE THREAD

**Issue by lumburovskalina** [code-kern-ai/refinery#228]
**Describe the bug**

**To Reproduce**
1. Go to project-settings page
2. Open the comments section and add a comment to a specific record (ex running_id 1)
3. Navigate to the labeling page and open the comments section for that specific record.
4. The comment is there, but if you navigate to the other records, the comment will be visible for them too which is wrong.

**Expected behavior**
The comments that are added for specific record should be visible only for that record. Currently if you add a comment for specific record on the labeling page, the expected behavior is happening. The same should be applied on the project-settings page.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 1.7.1.

**Comment by lumburovskalina** [comment]
The records on settings are only shown if the user navigates from the labeling page

**Comment by JWittmeyer** [comment]
missing an unsubscirption in the on destroy helper of the record helper class:
```if (this.activeRecordId) {
            CommentDataManager.unregisterPartialCommentRequests(this, [{ commentType: CommentType.RECORD, projectId: this.projectId, commentKey: this.activeRecordId }]);
        }
```

should do it
