### ISSUE TITLE
[BUG] - Attribute calculation seems to get stuck frequently

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/refinery#229]
**Describe the bug**
The bug attribute calculation seems to get stuck a lot. I noticed this behavior a couple of times now. It doesn't seem to be related to the intensity of the workload, as it seems to happen with light as well as more demanding tasks.

**To Reproduce**
1. Create a new attribute on the settings page
2. Try to create an attribute (for example from bricks), preferably one that finishes quickly (like reading time).
3. If it's not finishing within a couple of minutes, the attribute calc is probably stuck.

**Expected behavior**
Attribute calculation should finish and result in a usable attribute.

**Screenshots**
![2](https://user-images.githubusercontent.com/72195901/218454154-7780cfd2-7e38-45fc-be19-208f99ee0697.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Edge Chromium
 - Version: 1.7.1

**Additional context**
Our customer Büro Bardohn reported that in their project, the attribute calculation is running since two days.

**Comment by JWittmeyer** [comment]
No known occurrences after the changes in the attribute calculation session handling. Reopen if occurs again
