### ISSUE TITLE
[BUG] - start script

### ISSUE THREAD

**Issue by carlorscoelho** [code-kern-ai/refinery#240]
**Describe the bug**
There was an error (Error response from daemon: No such container: alfred) when run ./start 

**Issue**
1- carlos@carlosrodrigocoelho:~/refinery_test/refinery$ ./start
v1.8.0: Pulling from kernai/alfred
Digest: sha256:15fc59b24103ea7e9bebcbf08df1a76fb269778ed54331d320e3f173eaaaf0f1
Status: Image is up to date for kernai/alfred:v1.8.0
docker.io/kernai/alfred:v1.8.0
Error response from daemon: No such container: alfred

2- The ./stop wasn't working.

**Resolution**
For issue 1:
- delete the code > /dev/null 2>&1 at the end of line 17
- I have a space inside my path. Therefore, I need ed to change line 15 of the script to: -v "$PWD/refinery:/refinery" \, so putting the argument into quotation marks.

For issue2:
- docker compose -f refinery/docker-compose.yml down --remove-orphans
It does the same as the ./stop script, but with docker compose. Script only supports docker-compose and not docker compose.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser Chrome
 - Version 110.0.5481.177 (Official Build) (64-bit)

**Additional context**
Thank you, Felix Kirsch and Johannes Hötter for your support

**Comment by LeonardPuettmannKern** [comment]
Hello Carlos, 
thank you for reporting this bug. I saw that Felix and Johannes already provided support on Discord for that bug. If you need any further support for the usage of refinery, feel free to reach out anytime! :-)
