### ISSUE TITLE
[BUG] - Minio & qdrant storage is not persistant

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#27]
**Describe the bug**
In the current docker template file the object storage (minio) & qdrant have not volume attached. This means they are not saved persistently. 

**To Reproduce**
1. Create Project
2. Let Tokenization finish
3. Run Labelingfunction (docbin_full is used)
4. use stop script to shut down the app
5. use start script to start the app
6. run the function
7. Error

**Expected behavior**
Should work.

**Desktop (please complete the following information):**
 - OS:: all
 - Browser: all
 - Version: 1.0.0

**Comment by jhoetter** [comment]
@JWittmeyer can this be closed?
