### ISSUE TITLE
[BUG] - 'Prepare download' taking forever

### ISSUE THREAD

**Issue by hamzahassan66** [code-kern-ai/refinery#281]
Records not downloading.

I am trying to download records but in 'Export record data' tab 'Prepare download' is forever loading and not preparing zip file for download. My uploaded file is a text .xlsx with only a few records.
<img width="1106" alt="Screenshot 2024-12-08 212927" src="https://github.com/user-attachments/assets/35c7c4cd-1aa0-40c9-b689-eb01fe772358">

**Comment by JWittmeyer** [comment]
Hi @hamzahassan66,

thanks for reaching out. I tested with version 1.15 on my end and it worked without any issues. This usually indicates that something is up with the used data (e.g. some records that have special characters that get problematic to export) or the setup itself acting up.

To understand this issue further can you provide the logs of the docker container refinery gateway? (written: `refinery_refinery-gateway_1` or` refinery-refinery-gateway-1` depending on your Docker version).

To further test the issue could you also load the sample project Clickbait and try to export it to further narrow the issue down to either a general problem or a project related one?

**Comment by hamzahassan66** [comment]
Hi @JWittmeyer,

Thanks for responding. The attached short videos, project file and logs for refinery_refinery-gateway_1 container might give you more context about the issue. 

Export from sample projects work fine but new projects face this issue. But when I add labeling task to new project, the .zip file is prepared. 

[test_file.xlsx](https://github.com/user-attachments/files/18060100/test_file.xlsx)
[kern refinery logs.txt](https://github.com/user-attachments/files/18060101/kern.refinery.logs.txt)

https://github.com/user-attachments/assets/5fb82998-78a4-47a7-b79f-5e60f85d1af1

https://github.com/user-attachments/assets/b4b5d975-20d3-43d4-a239-3881aeb6d242

**Comment by JWittmeyer** [comment]
Hi @hamzahassan66,

thanks for the logs & videos. You are absolutely right, there was an issue with missing labeling tasks. I added a hotfix & a corresponding release for the effected container. 

For my version it now works also without the tasks. For you to access the newest/changed version please either pull the latest version of the refinery repository or change the version.json (located in `<resposity-folder>/refinery/version.json`) and change the entry for `GATEWAY` from `v1.15.0` to `v1.15.2`. After that running the start script again should solve the issue.

**Comment by hamzahassan66** [comment]
@JWittmeyer 

entry update resolved the issue. thanks a tonne 👍

**Comment by hamzahassan66** [comment]
@JWittmeyer 

entry update resolved the issue. thanks a tonne 👍
