### ISSUE TITLE
Derive labeling function from lookup list

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#39]
**Is your feature request related to a problem? Please describe.**
It is cumbersome to write a labeling function that always has the exact same structure if I want to use a lookup list for my labeling functions.

**Describe the solution you'd like**
Automatically create a labeling function given some lookup list (e.g. by asking for the attribute to apply this to, or by linking a lookup list to attributes)

**Describe alternatives you've considered**
Manually doing so

**Additional context**
\-

**Comment by JWittmeyer** [comment]
should be solved after the release of bricks and the bricks integrator

**Comment by jhoetter** [comment]
Solved with bricks
