### ISSUE TITLE
Further export options

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/refinery#46]
**Is your feature request related to a problem? Please describe.**
JSON is not always the desired format for exports, so there should be multiple options to select from.

**Describe the solution you'd like**
Provide multiple options (e.g. spreadsheet, CSV etc.) for the data export, and enable integrations to e.g. S3

**Describe alternatives you've considered**
Python SDK export options; the SDK export options and UI export options should be kept in sync.

**Additional context**
\-

**Comment by FelixKirsch** [comment]
https://github.com/code-kern-ai/refinery/issues/143 enables to choose from multiple export options (csv, xslx, json).
@JWittmeyer can we close the issue?

**Comment by JWittmeyer** [comment]
Can be closed for now - if new export formats are necessary we can reopen
