### ISSUE TITLE
File upload for project creation not working

### ISSUE THREAD

**Issue by leugh** [code-kern-ai/refinery#64]
Hello,

I am using the self-hosted version (v. 1.0). However, the file upload does not work when I try to create a new project. I don't get any error in the GUI, the screen just stays the same. When I press "Proceed" a second time, it tells me "Project title exists". And the project does indeed exist, however without any records.

Here is the outpout after staring it:
```
"UI:           http://localhost:4455/app/"
"Minio:        http:// =:7053"
"MailHog:      http://localhost:4436/"
```
I am running it on Windows.

I am unsure which logs could be relevant, but this is the Docker-output:

```
refinery-refinery-gateway-1 | ValueError: Invalid endpoint: http:// =:7053
refinery-refinery-gateway-1 | ERROR:graphql.execution.utils:Traceback (most recent call last):
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
refinery-refinery-gateway-1 |     return executor.execute(resolve_fn, source, info, **args)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
refinery-refinery-gateway-1 |     return fn(*args, **kwargs)
refinery-refinery-gateway-1 |   File "./graphql_api/query/transfer.py", line 65, in resolve_upload_credentials_and_id
refinery-refinery-gateway-1 |     project_id, user.id, file_name, file_type, file_import_options
refinery-refinery-gateway-1 |   File "./controller/transfer/manager.py", line 43, in get_upload_credentials_and_id
refinery-refinery-gateway-1 |     return s3.get_upload_credentials_and_id(org_id, project_id + "/" + str(task.id))
refinery-refinery-gateway-1 |   File "./submodules/s3/controller.py", line 367, in get_upload_credentials_and_id
refinery-refinery-gateway-1 |     response = minio.get_upload_credentials_and_id(target_bucket)
refinery-refinery-gateway-1 |   File "./submodules/s3/connections/minio.py", line 172, in get_upload_credentials_and_id
refinery-refinery-gateway-1 |     use_ssl=False,
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 93, in client
refinery-refinery-gateway-1 |     return _get_default_session().client(*args, **kwargs)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 275, in client
refinery-refinery-gateway-1 |     aws_session_token=aws_session_token, config=config)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 874, in create_client
refinery-refinery-gateway-1 |     client_config=config, api_version=api_version)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 93, in create_client
refinery-refinery-gateway-1 |     verify, credentials, scoped_config, client_config, endpoint_bridge)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 362, in _get_client_args
refinery-refinery-gateway-1 |     verify, credentials, scoped_config, client_config, endpoint_bridge)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 108, in get_client_args
refinery-refinery-gateway-1 |     proxies_config=new_config.proxies_config)
refinery-refinery-gateway-1 |   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 335, in create_endpoint
refinery-refinery-gateway-1 |     raise ValueError("Invalid endpoint: %s" % endpoint_url)
refinery-refinery-gateway-1 | graphql.error.located_error.GraphQLLocatedError: Invalid endpoint: http:// =:7053
```
I have tried installing it via pip and directly from the repo. I have also tried different browsers.

Best,
Leo

**Comment by jhoetter** [comment]
Hi @leugh, thanks for trying the self-hosted version. It looks like the Minio URL is erroneous, there should be some valid endpoint (which you can also see in the error message `graphql.error.located_error.GraphQLLocatedError: Invalid endpoint: http:// =:7053`). We will look into this and get back to you :)

**Comment by SirDegraf** [comment]
Hi @leugh, it looks like the resolving of your IPv4 Address is not working as expected. For Windows Users, we make use of the ipconfig command. Could you maybe execute ipconfig in your terminal and send me the output here or to my Mail simon.degraf@kern.ai, so I can look into wheter it differs from what we expect?

**Comment by leugh** [comment]
@SirDegraf I have sent you the output via e-mail as I am unsure if it contains confidential information that I shouldn’t post publicly. Thanks for your help!

**Comment by SirDegraf** [comment]
@leugh thank you very much for helping us improve our tool. Unfortunately, the mail was not delivered to my address [simon.degraf@kern.ai](mailto:simon.degraf@kern.ai). Could you send it again to info@kern.ai?

**Comment by leugh** [comment]
> @leugh thank you very much for helping us improve our tool. Unfortunately, the mail was not delivered to my address [simon.degraf@kern.ai](mailto:simon.degraf@kern.ai). Could you send it again to [info@kern.ai](mailto:info@kern.ai)?

Done - hope it came through now.

**Comment by leugh** [comment]
That was it - perfect!

Many thanks!

**Comment by xavialex** [comment]
Hi everyone. I'm afraid I'm experiencing the same error: once refinery is launched, in the GUI, while creating a new project, the Upload file functionality is disabled. I'm not sure if this is the same problem as leugh, since I'm working on a Mac and the IP adress seems to be correctly gathered. 

Any thoughts on this?. Thanks in advance
