### ISSUE TITLE
[UX] - Go back button on the notification center

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#94]
**What would you improve?**
I suggest adding a "go back" button on the notification center page. After navigating to the notification center, I cannot navigate back to the previous page. Or to be clear, just by using the browser's "go back" functionality. It would be nice to have this functionality also inside the application, especially when working with the maximized screen.

**Comment by jhoetter** [comment]
Luca (our freelance designer) suggested that we turn the notification center into a modal, such that we also don't lose sense of context :) This would solve this issue, too

**Comment by FelixKirsch** [comment]
That sounds even better :)
